config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :achievements

  namespace :api do
    resources :achievements, only: [:index]
  end


  root to: 'welcome#index'
end

app/models/achievement.rb
class Achievement < ApplicationRecord
    # association
    belongs_to :user
    # validation, we can customise different validations.
    validates :title, presence: true
    validates :user, presence: true
    validates :title, uniqueness: {
        scope: :user_id,
        message: "You can't have two achievements with the same title"
    }
    # this means that this validation applies to the scope of users.
    # validate :unique_title_for_one_user

    

    enum privacy: [:public_access, :private_access, :friends_access]

    mount_uploader :cover_image, CoverImageUploader

    # instance method, which converts markdown into html.
    def description_html
        Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(description)
    end

    def silly_title
        "#{title} by #{user.email}"
    end

    def self.by_letter(letter)
        includes(:user).where("title LIKE ?", "#{letter}%").order("users.email")
        # the percent sign means any letter in SQL.
        # ordering records by users' email field.
    end

    def self.get_public_achievements
    end

    # private

    # def unique_title_for_one_user 
    #     existing_achievement = Achievement.find_by(title: title)
    #     # using the current achievement title to find another achievement with the same title in the db

    #     if existing_achievement && existing_achievement.user == user
    #     # if the exsisting achievement actually exsists and the exsisting achievement user is the same aa this particular user then ..
    #         errors.add(:title, "You can't have two achievements with the same title")
    #     end
    # end

    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController

    before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy ]
    # devise before action, devise helper iself is authenticate user, specify what actions.
    before_action :owners_only, only: [:edit, :update, :destroy]


    # when we create new actions in the controller spec we need to apply the action method here.

    def index
        @achievement = Achievement.get_public_achievements
        # instead of public_access we use get_public_achievements
    end

    def new 
        @achievement = Achievement.new
    end

    def create
        # service = CreateAchievement.new(params[:achievement], current_user)
        # service.create
        # if service.created?
        #     UserMailer.achievement_created(current_user.email, @achievement.id).deliver_now
        #     # what kind of arguments it takes, deliver this email now
        #     redirect_to achievement_path(service.achievement)
        #     # this means that we need to stub it because this is dependencies message.
        # else
        #     @achievement = service.achievement
        #     render :new
        # end

        @achievement = Achievement.new(achievement_params)
        @achievement.user = current_user
        if @achievement.save
            UserMailer.achievement_created(current_user.email, @achievement.id).deliver_now
            tweet = TwitterService.new.tweet(@achievement.title)
            # when an achievement has been created the twitter service tweets the achievement message with the title of the created achievement 
            redirect_to achievement_url(@achievement), notice: "Achievement has been created, We tweeted for you! #{tweet.url}"
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @achievement.update_attributes(achievement_params)
            redirect_to achievement_path
        else
            render :edit
        end
        # we have a ssuccess path and a fail(invalid) path.
        
    end

    def show
        @achievement = Achievement.find(params[:id])
    end

    def destroy
        @achievement.destroy
        # actually destroys the selected achievement id.
        redirect_to achievement_path
    end

    private

    def achievement_params
        params.require(:achievement).permit(:title, :description, :privacy, :cover_image, :featured )
    end

    def owners_only
        @achievement = Achievement.find(params[:id])
        if current_user != @achievement.user
            redirect_to achievement_path
        end
    end
end

app/controllers/api/achievements_controller.rb
class Api::AchievementsController < ApiController
    def index
        # p request.headers["Content-type"]
        achievements = Achievement.public_access
        render json: achievements

    end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
    protect_from_forgery with: :null_session

    before_action :validate_header

    private

    def validate_header
        if request.headers["Content-Type"] != 'application/vnd.api+json'
            render json: {} , status: 400
            return
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def find
        @achievement = Achievement.new
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/achievements/new.html.erb
<%= simple_form_for(Achievement.new) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :privacy, collection: Hash[Achievement.privacies.map {|k, v| [k.split('_').first.capitalize, k]}] %>
        <%# # mapping the privacies hash into a new hash with key and value. %>
    <%= f.input :featured, label: 'Featured achievement' %> 
    <%= f.input :cover_image, as: :file %>
    <%= f.submit 'Create Achievement', class: 'btn btn-primary' %>
<% end %>

app/views/achievements/show.html.erb
<h1><%= @achievement.title%></h1>
<div>
<%= @achievement.description_html.html_safe %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

		<div class = "container-fluid">
			<nav class="navbar navbar-expand-lg navbar-light bg-light">
				<div class = "navbar-header">
					<button type = "button" class = "navbar-toggle" data-toggle = "collapse" data-target = ".navbar-ex1-collapse">
						<span class = "sr-only"> toggle navigation </span>
						<span class = "icon-bar">  </span>
						<span class = "icon-bar">  </span>
						<span class = "icon-bar">  </span>
					</button>
					<a class= "navbar-brand" href="/"> app </a>
				</div>

				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav mr-auto">
						<li><%= link_to 'New Achievement', new_achievement_path %> </li>
					</ul>
				</div>
			</nav>

			<% if flash[:notice] %>
				<div class = "alert alert_info">
					<%= flash[:notice] %>
				</div>
			<% end%>


			<%= yield %>
		</div>
    
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome<h1>